version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "rack"
      versions: ["3.1.x", "3.2.x"] # unknown breaking test change starting in 3.1
